CREATE DATABASE LOCADORA;
GO

USE LOCADORA;
GO

CREATE TABLE EMPRESA (
idEmpresa TINYINT PRIMARY KEY IDENTITY (1,1),
);
GO

CREATE TABLE VEICULOS (
idVeiculo SMALLINT PRIMARY KEY IDENTITY (1,1),
idEmpresa TINYINT FOREIGN KEY REFERENCES EMPRESA(idEmpresa),
idModelo SMALLINT FOREIGN KEY REFERENCES MODELO(idModelo),
placa char (7) NOT NULL UNIQUE
);
GO

DROP TABLE VEICULOS


CREATE TABLE MARCA (
idMarca TINYINT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR (30) NOT NULL
);
GO

CREATE TABLE MODELO (
idModelo SMALLINT PRIMARY KEY IDENTITY (1,1),
idMarca TINYINT FOREIGN KEY REFERENCES MARCA(idMarca),
descricao varchar (30) NOT NULL
);
GO

CREATE TABLE CLIENTES (
idClientes SMALLINT PRIMARY KEY IDENTITY (1,1),
nome VARCHAR (30) NOT NULL,
cpf CHAR (11) NOT NULL UNIQUE
);
GO

CREATE TABLE ALUGUEIS (
idAluguel SMALLINT PRIMARY KEY IDENTITY (1,1),
idVeiculo SMALLINT FOREIGN KEY REFERENCES VEICULOS(idVeiculo),
idClientes SMALLINT FOREIGN KEY REFERENCES CLIENTES(idClientes),
data_inicio  DATETIME NOT NULL DEFAULT GETDATE(),
data_fim DATETIME NOT NULL DEFAULT GETDATE(),
);
GO